language: node_js
node_js:
  - "10"
install:
  - yarn install
script:
  - yarn lint
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
cache: yarn

